const data = {  _id: '1',
    products: [
      {  _id: '1',
        name: 'Apples',
        slug: 'apples',
        category: 'Fruits',
        image: '/img/Apples.jpg', 
        price: 120,
        countInStock: 10,
        rating: 3.5,
        numReviews: 30,
        description: 'High quality apples',
      },
      {  _id: '2',
        name: 'Banana',
        slug: 'banana',
        category: 'Fruits',
        image: '/img/Banana.jpg', // 679px × 829px
        price: 80,
        countInStock: 10,
        rating: 4.5,
        numReviews: 16,
        description: 'High quality Banana',
      },
      {  _id: '3',
        name: 'Grapes',
        slug: 'grapes',
        category: 'Fruits',
        image: '/img/Grapes.jpg', // 679px × 829px
        price: 100,
        countInStock: 10,
        rating: 3.5,
        numReviews: 10,
        description: 'Tasty Grapes',
      },
      {  _id: '4',
        name: 'Oranges',
        slug: 'orange',
        category: 'Fruits',
        image: '/img/Oranges.jpg', // 679px × 829px
        price: 100,
        countInStock: 10,
        rating: 5,
        numReviews: 10,
        description: 'high quality Oranges',
      },
      {  _id: '5',
        name: 'Strawberry',
        slug: 'strawberries',
        category: 'Fruits',
        image: '/img/Strawberry.jpg', // 679px × 829px
        price: 200,
        countInStock: 10,
        rating: 3.5,
        numReviews: 10,
        description: 'Yummy Strawberries',
      },
      {  _id: '6',
        name: 'Papaya',
        slug: 'papaya',
        category: 'Fruits',
        image: '/img/Papaya.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 20,
        description: 'Healthy papaya',
      },
      {  _id: '7',
        name: 'Mangoes',
        slug: 'mangoes',
        category: 'Fruits',
        image: '/img/Mangoes.jpg', // 679px × 829px
        price: 120,
        countInStock: 0,
        rating: 2.5,
        numReviews: 4,
        description: 'high quality mangoes',
      },
      {  _id: '8',
        name: 'Tomatoes',
        slug: 'tomatoes',
        category: 'Veggies',
        image: '/img/tomato.jpg', // 679px × 829px
        price: 50,
        countInStock: 10,
        rating: 5,
        numReviews: 25,
        description: 'high quality Tomato',
      },
      {  _id: '9',
        name: 'Potatoes',
        slug: 'potatoes',
        category: 'Veggies',
        image: '/img/Aloo.jpg', // 679px × 829px
        price: 20,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality potatoes',
      },
      {  _id: '10',
        name: 'Onions',
        slug: 'onions',
        category: 'Veggies',
        image: '/img/Onions.jpg', // 679px × 829px
        price: 50,
        countInStock: 10,
        rating: 3.5,
        numReviews: 20,
        description: 'high quality apples',
      },
      {  _id: '11',
        name: 'Lemons',
        slug: 'lemons',
        category: 'Veggies',
        image: '/img/Lemons.jpg', // 679px × 829px
        price: 10,
        countInStock: 10,
        rating: 2.5,
        numReviews: 15,
        description: 'high quality apples',
      },
      {  _id: '12',
        name: 'Green Chillies',
        slug: 'green chillies',
        category: 'Veggies',
        image: '/img/Chilly.jpg', // 679px × 829px
        price: 10,
        countInStock: 10,
        rating: 3.5,
        numReviews: 20,
        description: 'high quality apples',
      },
    ],
  };
  module.exports = data;